#!/usr/bin/env python3
"""
SeamlyAI - OpenSpec Project Initializer
Запустите этот скрипт в корневой папке проекта.
"""

import os
from pathlib import Path

FILES = {
    "openspec/project.md": "# SeamlyAI — AI-ориентированная САПР для конструирования одежды\n\n## Project Purpose\nСоздание форка Seamly2D с интеграцией AI-функций, улучшенным UX и бесшовной интеграцией с 3D-пакетами (CLO 3D, Blender). Целевая аудитория: независимые дизайнеры, малые ателье, энтузиасты.\n\n## Core Principles\n1. **Инженерная точность** — использование проверенной параметрической базы Seamly2D\n2. **AI-ассистент** — автоматизация рутинных задач, генерация лекал по эскизу\n3. **Бесшовная интеграция** — корректный экспорт в форматы, понятные CLO 3D и Blender\n4. **Современный UX** — интерфейс в стиле Figma/современных дизайн-инструментов\n5. **Доступность** — Freemium-модель с открытым ядром\n\n## Technology Stack\n- **Core**: C++/Qt (наследуется от Seamly2D)\n- **AI Layer**: Python FastAPI микросервис + интеграция с LLM (Claude/Codex)\n- **Frontend (опционально для веб-версии)**: React/TypeScript\n- **3D Integration**: Экспорт в DXF-ASTM, OBJ, FBX\n- **Deployment**: Electron для десктоп-версии, Docker для backend-сервисов\n",

    "openspec/AGENTS.md": "# SeamlyAI - AI Agent Instructions\n\n## Role\nВы — AI-агент, отвечающий за разработку SeamlyAI, форка Seamly2D с AI-функциями.\n\n## Communication Style\n- Отвечайте на русском языке (пользователь русскоязычный)\n- Предлагайте конкретные технические решения, а не общие рассуждения\n- Указывайте конкретные файлы и функции при описании изменений\n\n## Development Rules\n1. Все изменения должны соответствовать спецификациям в `/openspec/specs/`\n2. При добавлении новой функциональности — обновляйте соответствующую спецификацию\n3. Перед реализацией сложной функции — предложите дизайн-документ\n4. Код должен быть документирован на русском языке (комментарии)\n\n## Git Workflow\n1. Все изменения делаются в ветке `feature/*` от `main`\n2. Pull Request должен содержать: описание изменений, ссылку на спецификацию\n3. После ревью — мержим в `main`\n\n## Priority Order\n1. **Phase 1**: Fork and Setup (создание структуры, CI/CD)\n2. **Phase 2**: Export Fix (DXF-ASTM, OBJ, FBX)\n3. **Phase 3**: AI Service (FastAPI + LLM)\n4. **Phase 4**: UI Modernization\n5. **Phase 5**: Monetization Layer\n6. **Phase 6**: Testing and Release\n",

    "openspec/changes/init-project/proposal.md": "# Proposal: Initial Project Setup — SeamlyAI\n\n## Why\nSeamly2D — мощный open-source инструмент, но он страдает от:\n1. Устаревшего UX, отпугивающего дизайнеров\n2. Проблем с экспортом в CLO 3D (потеря кривых при конвертации)\n3. Отсутствия AI-функций для автоматизации\n\nРынок требует решения, которое сочетает инженерную точность с современным UX и AI-ассистентом.\n\n## What Changes\n- **Форк Seamly2D** как база\n- **AI-ассистент**: генерация лекал по эскизу, автоматическая градация, интеллектуальный подбор параметров\n- **Исправленный экспорт**: корректный DXF-ASTM для CLO 3D, OBJ/FBX для Blender\n- **Переработанный UI**: современный, интуитивный, адаптивный\n\n## What Stays Same\n- Параметрическое ядро и методики конструирования Seamly2D\n- Открытая лицензия для базового функционала\n\n## Impact\n- **Пользователи**: получают доступный инструмент с AI-функциями\n- **Разработчики**: форк позволяет независимо развивать продукт\n- **Бизнес**: Freemium-модель с платными AI-функциями и облачными сервисами\n",

    "openspec/changes/init-project/design.md": "# Design: SeamlyAI Architecture\n\n## Architectural Decisions\n\n### 1. Fork Strategy\n- **Decision**: Форкнуть Seamly2D, а не Valentina\n- **Reason**: Seamly2D имеет более активное сообщество и открыто заявляет о намерении двигаться в сторону 3D\n\n### 2. AI Integration Architecture\n- **Decision**: Вынести AI-логику в отдельный микросервис на Python/FastAPI\n- **Reason**:\n  - Независимость от основного C++ кода\n  - Легче экспериментировать с разными LLM\n  - Возможность развернуть как облачный сервис для монетизации\n\n### 3. Export Fix Strategy\n- **Problem**: Seamly2D экспортирует кривые как множество мелких отрезков, что ломает работу в CLO 3D\n- **Solution**: Реализовать генерацию корректного DXF-ASTM с маркировкой точек кривых (spline-информация)\n\n### 4. UI Modernization\n- **Decision**: Использовать Qt Quick/QML для переработки интерфейса\n- **Alternative**: Electron + React (если делать веб-версию)\n- **Reason**: Qt Quick позволяет сохранить производительность нативного приложения с современным дизайном\n\n### 5. Monetization Architecture\n- **Freemium Model**:\n  - Бесплатно: Базовое конструирование, локальный AI (ограниченный), экспорт в базовые форматы\n  - Платно: Cloud AI (неограниченный), приоритетный экспорт, командная работа, облачное хранилище\n",

    "openspec/changes/init-project/tasks.md": "# Tasks: SeamlyAI Implementation\n\n## Phase 1: Core Fork and Setup\n- [ ] 1.1 Fork Seamly2D repository\n- [ ] 1.2 Set up CI/CD pipeline (GitHub Actions)\n- [ ] 1.3 Rename project to SeamlyAI\n- [ ] 1.4 Update all license headers\n- [ ] 1.5 Create initial project documentation\n\n## Phase 2: Export Fix\n- [ ] 2.1 Analyze current DXF export implementation\n- [ ] 2.2 Implement DXF-ASTM export with spline support\n- [ ] 2.3 Test export in CLO 3D\n- [ ] 2.4 Implement OBJ export for Blender\n- [ ] 2.5 Implement FBX export for Blender\n- [ ] 2.6 Add export validation\n\n## Phase 3: AI Service\n- [ ] 3.1 Set up Python FastAPI service\n- [ ] 3.2 Implement LLM integration (Claude API)\n- [ ] 3.3 Implement pattern generation from sketch\n- [ ] 3.4 Implement natural language parameter adjustment\n- [ ] 3.5 Implement AI-assisted gradation\n- [ ] 3.6 Create API documentation\n\n## Phase 4: UI Modernization\n- [ ] 4.1 Design new UI mockups\n- [ ] 4.2 Migrate to Qt Quick/QML\n- [ ] 4.3 Implement command palette\n- [ ] 4.4 Implement dark/light theme\n- [ ] 4.5 Implement AI assistant panel\n- [ ] 4.6 Redesign properties panel\n\n## Phase 5: Monetization Layer\n- [ ] 5.1 Implement license management system\n- [ ] 5.2 Set up payment processing (Stripe)\n- [ ] 5.3 Implement cloud storage backend\n- [ ] 5.4 Implement team collaboration features\n- [ ] 5.5 Create landing page with pricing\n- [ ] 5.6 Set up analytics for usage tracking\n\n## Phase 6: Testing and Release\n- [ ] 6.1 Write unit tests for core functionality\n- [ ] 6.2 Write integration tests for AI service\n- [ ] 6.3 User acceptance testing\n- [ ] 6.4 Create installer packages (Windows, macOS, Linux)\n- [ ] 6.5 Launch beta program\n- [ ] 6.6 Public release\n",

    "openspec/specs/pattern-generation/spec.md": "# Pattern Generation Specification\n\n## ADDED Requirements\n\n### Requirement: AI-Pattern Generation from Sketch\nThe system SHALL generate parametric patterns from user-uploaded sketches or photographs.\n\n#### Scenario: Generate basic bodice from photo\n- **GIVEN** a user uploads a photo of a dress sketch\n- **AND** the user provides body measurements (height, bust, waist, hip)\n- **WHEN** the user invokes the AI pattern generator\n- **THEN** the system returns a parametric pattern with all measurements applied\n- **AND** the pattern is editable in the 2D workspace\n\n#### Scenario: Pattern generation fails\n- **GIVEN** a user uploads a low-quality or unrecognizable sketch\n- **WHEN** the AI pattern generator fails to generate a valid pattern\n- **THEN** the system SHALL display a clear error message\n- **AND** suggest alternative approaches (e.g., use template, manual drawing)\n\n### Requirement: AI-Assisted Gradation\nThe system SHALL automatically grade patterns across multiple sizes using AI.\n\n#### Scenario: Grade pattern to size range\n- **GIVEN** a user has a finished pattern in size M\n- **WHEN** the user selects \"Generate Size Range\" with sizes XS to XL\n- **THEN** the system generates all intermediate sizes\n- **AND** each size follows standard industry grading rules\n- **AND** the user can review and adjust each grade individually\n\n### Requirement: Natural Language Parameter Adjustment\nThe system SHALL allow users to modify pattern parameters using natural language.\n\n#### Scenario: Adjust sleeve length by voice\n- **GIVEN** a user has an open pattern with a sleeve\n- **WHEN** the user types or speaks \"make sleeves 5 cm shorter\"\n- **THEN** the system automatically updates the sleeve pattern\n- **AND** all dependent measurements (armhole, cuff) are updated accordingly\n",

    "openspec/specs/format-conversion/spec.md": "# Format Conversion Specification\n\n## ADDED Requirements\n\n### Requirement: DXF-ASTM Export for CLO 3D\nThe system SHALL export patterns in DXF-ASTM format with preserved curve information.\n\n#### Scenario: Export to CLO 3D\n- **GIVEN** a user has a completed 2D pattern\n- **WHEN** the user selects \"Export to CLO 3D (DXF-ASTM)\"\n- **THEN** the system generates a DXF file with:\n  - All splines correctly marked as splines (not polyline approximations)\n  - Notches and grain lines preserved as metadata\n  - Pattern pieces named and grouped\n  - ASTM format compliant\n\n#### Scenario: Export fails validation\n- **GIVEN** a user attempts to export a pattern with self-intersecting curves\n- **WHEN** the export is initiated\n- **THEN** the system SHALL validate the pattern geometry\n- **AND** display a warning with specific error locations\n- **AND** allow the user to fix issues before retrying\n\n### Requirement: OBJ/FBX Export for Blender\nThe system SHALL export patterns as 3D meshes for use in Blender.\n\n#### Scenario: Export flat pattern as OBJ\n- **GIVEN** a user has a 2D pattern\n- **WHEN** the user selects \"Export to OBJ\"\n- **THEN** the system generates a flat 3D mesh of the pattern\n- **AND** includes material information for fabric simulation\n\n### Requirement: Import from Existing CAD Formats\nThe system SHALL import patterns from common CAD formats (DXF, AAMA, ASTM).\n\n#### Scenario: Import DXF from competitor CAD\n- **GIVEN** a user has a DXF file from Gerber or Lectra\n- **WHEN** the user selects \"Import DXF\"\n- **THEN** the system imports the pattern with:\n  - All geometry intact\n  - Measurements preserved\n  - Grading information (if present) imported\n",

    "openspec/specs/user-interface/spec.md": "# User Interface Specification\n\n## ADDED Requirements\n\n### Requirement: Modern Figma-Inspired UI\nThe system SHALL provide a modern, intuitive user interface inspired by Figma and contemporary design tools.\n\n#### Scenario: First-time user opens the app\n- **GIVEN** a user launches SeamlyAI for the first time\n- **WHEN** the application loads\n- **THEN** the user sees:\n  - A clean, minimal toolbar with clear icons\n  - A contextual properties panel on the right\n  - A command palette accessible via Cmd/Ctrl+K\n  - An AI assistant chat panel on the left\n\n#### Scenario: Command palette usage\n- **GIVEN** a user is working on a pattern\n- **WHEN** the user presses Cmd/Ctrl+K\n- **THEN** a searchable command palette opens\n- **AND** the user can search for actions by name\n- **AND** the palette shows keyboard shortcuts for each action\n\n### Requirement: Dark/Light Theme Support\nThe system SHALL support both dark and light themes.\n\n#### Scenario: Toggle theme\n- **GIVEN** a user is working in the application\n- **WHEN** the user selects \"Toggle Theme\" from the menu\n- **THEN** the interface switches between dark and light mode\n- **AND** all UI elements update immediately\n- **AND** the preference is saved for future sessions\n\n### Requirement: AI Assistant Panel\nThe system SHALL provide a persistent AI assistant panel for natural language interaction.\n\n#### Scenario: Ask AI for help\n- **GIVEN** a user is stuck on a pattern modification\n- **WHEN** the user types \"How do I add a dart to this bodice?\" in the AI panel\n- **THEN** the system provides step-by-step instructions\n- **AND** optionally offers to execute the steps automatically\n",

    "openspec/specs/monetization/spec.md": "# Monetization Specification\n\n## ADDED Requirements\n\n### Requirement: Freemium License Model\nThe system SHALL offer both free and premium tiers.\n\n#### Scenario: Free tier usage\n- **GIVEN** a user downloads SeamlyAI\n- **WHEN** the user uses the application without a license\n- **THEN** the user has access to:\n  - Full pattern construction and editing\n  - Limited AI generations (5 per day)\n  - Local AI processing (slower, less accurate)\n  - Export to DXF (basic), SVG, PDF\n\n#### Scenario: Premium tier features\n- **GIVEN** a user purchases a premium license\n- **WHEN** the user logs in with their premium account\n- **THEN** the user has access to:\n  - Unlimited AI generations\n  - Cloud AI processing (faster, more accurate)\n  - Premium export formats (DXF-ASTM with full curve data)\n  - Cloud storage and syncing\n  - Team collaboration features\n  - Priority support\n\n### Requirement: Cloud Storage for Premium Users\nThe system SHALL provide cloud storage for patterns and preferences.\n\n#### Scenario: Save pattern to cloud\n- **GIVEN** a premium user is working on a pattern\n- **WHEN** the user saves the pattern\n- **THEN** the pattern is synced to the user's cloud storage\n- **AND** is accessible from other devices\n\n#### Scenario: Collaborate on a pattern\n- **GIVEN** two premium users are working on the same team\n- **WHEN** one user modifies a shared pattern\n- **THEN** the other user sees the changes in real-time (or upon refresh)\n- **AND** version history is maintained\n",
}

def create_files():
    project_root = Path.cwd()
    for filepath, content in FILES.items():
        full_path = project_root / filepath
        full_path.parent.mkdir(parents=True, exist_ok=True)
        if full_path.exists():
            print(f"File exists, skip: {filepath}")
            continue
        full_path.write_text(content, encoding='utf-8')
        print(f"Created: {filepath}")
    print("Done!")

if __name__ == "__main__":
    print("SeamlyAI - OpenSpec Project Initializer")
    print("Creating structure in:", Path.cwd())
    create_files()
